### PR TITLE
fix early crash failed due to incomplete readiness

### LINKED ISSUE #593: chain index sync loop breaks loop on error with no error handling or restart
zaino-state/src/chain_index.rs::431

chain index owns the sync loop handle but does not handle errors. sync will silently fail and not recover.

### PR DESCRIPTION
**Pull request by zancas**
Fixes: #593

### CODE REVIEW

**Comment by zancas** [comment]
I now have regression tests showing that ErrorFromSource only promotes to CriticalError in an expected case, so I can return to debugging the integration test "get_block_header" knowing that CriticalError on sync_loop has another source.

**Comment by zancas** [comment]
e.g.

`cargo nextest run --test state_service zebra::lightwallet_indexer::get_block_`

reliably produces passing tests!

**Comment by zancas** [comment]
The bug was that poll_until_ready was not called until after generate_blocks was called, which depends on "readiness".

There are other improvements in the PR including better error reporting and logging.

**Comment by zancas** [comment]
Ten passes in a row!

```bash
for i in $(seq 1 2); do echo "=== Run $i ===" && cargo nextest run -j1 --test state_service -E 'test(=zebra::lightwallet_indexer::get_block_header)'; done
=== Run 1 ===
        PASS [  25.905s] (1/1) integration-tests::state_service zebra::lightwallet_indexer::get_block_header
────────────
     Summary [  25.905s] 1 test run: 1 passed, 49 skipped

=== Run 2 ===
        PASS [  26.530s] (1/1) integration-tests::state_service zebra::lightwallet_indexer::get_block_header
────────────
     Summary [  26.530s] 1 test run: 1 passed, 49 skipped

=== Run 3 ===
        PASS [  26.099s] (1/1) integration-tests::state_service zebra::lightwallet_indexer::get_block_header
────────────
     Summary [  26.100s] 1 test run: 1 passed, 49 skipped

=== Run 4 ===
        PASS [  26.697s] (1/1) integration-tests::state_service zebra::lightwallet_indexer::get_block_header
────────────
     Summary [  26.717s] 1 test run: 1 passed, 49 skipped

=== Run 5 ===
        PASS [  24.262s] (1/1) integration-tests::state_service zebra::lightwallet_indexer::get_block_header
────────────
     Summary [  24.262s] 1 test run: 1 passed, 49 skipped

=== Run 6 ===
        PASS [  26.165s] (1/1) integration-tests::state_service zebra::lightwallet_indexer::get_block_header
────────────
     Summary [  26.166s] 1 test run: 1 passed, 49 skipped

=== Run 7 ===
        PASS [  26.090s] (1/1) integration-tests::state_service zebra::lightwallet_indexer::get_block_header
────────────
     Summary [  26.090s] 1 test run: 1 passed, 49 skipped

=== Run 8 ===
        PASS [  25.942s] (1/1) integration-tests::state_service zebra::lightwallet_indexer::get_block_header
────────────
     Summary [  25.942s] 1 test run: 1 passed, 49 skipped

=== Run 9 ===
        PASS [  26.646s] (1/1) integration-tests::state_service zebra::lightwallet_indexer::get_block_header
────────────
     Summary [  26.646s] 1 test run: 1 passed, 49 skipped

=== Run 10 ===
        PASS [  25.944s] (1/1) integration-tests::state_service zebra::lightwallet_indexer::get_block_header
────────────
     Summary [  25.945s] 1 test run: 1 passed, 49 skipped
```

**Comment by zancas** [comment]
In contrast against current `dev`:  _commit 2c657847aec0de360b430b014e01a3a56d4b11d1_ 

The test passed only 6 out of 20 runs executed with this script:

```bash
PASS=0; TOTAL=0; for i in $(seq 1 20); do TOTAL=$((TOTAL + 1)); echo $i; if cargo nextest run -j1 --test state_service -E 'test(=zebra::lightwallet_indexer::get_block_header)' &>/dev/null; then PASS=$((PASS + 1)); fi; done; echo "${PASS}/${TOTAL} passed"
```

Taken with my last comment this is unambiguous evidence of a significant test-bug fix.

**Comment by zancas** [comment]
Note this ALSO includes a change in sync_loop behavior in production!

File: integration-tests/zaino-testutils/src/lib.rs [hunk 1]
```diff
@@ -514,8 +512,15 @@ where
             .await;
         }
 
+        // Generate an extra block to turn on NU5 and NU6,
```
Comment (zancas) [inline integration-tests/zaino-testutils/src/lib.rs:515]: I should research why this is asserted and link to the explanatory resource.

File: zainod/src/indexer.rs [hunk 2]
```diff
@@ -150,7 +150,26 @@ where
     /// Checks indexers status and servers internal statuses for either offline of critical error signals.
     fn check_for_critical_errors(&self) -> bool {
         let status = self.status_int();
-        status == 5 || status >= 7
+        if status == 5 || status >= 7 {
```
Comment (nachog00) [inline zainod/src/indexer.rs:153]: This is probably covered by the `NamedStatus` automatic status logging.
Running with `RUST_LOG=debug` (or something pretty similar) you'll get them turned on.

File: packages/zaino-state/src/chain_index.rs [hunk 3]
```diff
@@ -545,71 +545,103 @@ impl<Source: BlockchainSource> NodeBackedChainIndex<Source> {
 
     #[instrument(name = "ChainIndex::start_sync_loop", skip(self))]
     pub(super) fn start_sync_loop(&self) -> tokio::task::JoinHandle<Result<(), SyncError>> {
```
Comment (nachog00) [inline packages/zaino-state/src/chain_index.rs:547]: This function is so convoluted already, with several loops, spwans, helper functions etc, that the whole block looks to me like a clear candidate to become it's own module.

Arguments like "I like that this function is clearly only meant to be used i this scope" like for example `source_error` or `exponential_backoff` are relevant ONLY to `start_sync_loop` can be easily met with module visibility features.

File: zainod/src/indexer.rs (hunk 2 above)
Comment (zancas) [reply zainod/src/indexer.rs:153]: Tracked by https://github.com/zingolabs/zaino/issues/980

File: packages/zaino-state/src/chain_index.rs (hunk 3 above)
Comment (zancas) [reply packages/zaino-state/src/chain_index.rs:547]: Captured here:  https://github.com/zingolabs/zaino/issues/981

File: zaino-state/src/chain_index/source.rs [hunk 4]
```diff
@@ -810,6 +722,7 @@ pub(crate) mod test {
         treestates: Vec<(Vec<u8>, Vec<u8>)>,
         hashes: Vec<BlockHash>,
         active_chain_height: Arc<AtomicU32>,
+        force_requests_against_source_to_fail: Arc<std::sync::atomic::AtomicBool>,
```
Comment (nachog00) [inline zaino-state/src/chain_index/source.rs:725]: I think `chaindex` is the wrong place for validator connection retries logic. It deserves to be en capsuled and managed completely by `ValidatorConnector` or whatever equivalent abstraction provides access to the validator.

Comment (zancas) [reply zaino-state/src/chain_index/source.rs:725]: Covered by:  https://github.com/zingolabs/zaino/issues/982

File: zaino-state/src/chain_index/tests.rs [hunk 5]
```diff
@@ -97,6 +97,36 @@ mod mockchain_tests {
         (blocks, indexer, index_reader, source)
     }
 
+    /// Regression test: a transient source failure should not kill the sync loop.
```
Comment (nachog00) [inline zaino-state/src/chain_index/tests.rs:100]: #982 addresses this. If the validator connection got it's own retry-aware abstraction, then consumer wouldn't ever need to worry about it (on the transient case at least, it would if the validator was truly down)

File: zaino-state/src/chain_index/non_finalised_state.rs [hunk 6]
```diff
@@ -93,11 +93,13 @@ impl std::error::Error for MissingBlockError {}
...
-    /// The backing validator node returned corrupt, invalid, or incomplete data
-    /// TODO: This may not be correctly disambibuated from temporary network issues
-    /// in the fetchservice case.
+    /// The backing validator node returned corrupt, invalid, or incomplete data.
     #[error("failed to connect to validator: {0:?}")]
     ValidatorConnectionError(NodeConnectionError),
+    /// The blockchain source returned a transient error (e.g. node temporarily
+    /// unreachable). The sync loop should retry.
+    #[error("transient source error: {0}")]
+    ErrorFromSource(Box<dyn std::error::Error + Send>),
```
Comment (nachog00) [inline zaino-state/src/chain_index/non_finalised_state.rs:102]: why dyn?

Comment (zancas) [reply zaino-state/src/chain_index/non_finalised_state.rs:102]: Issued:  https://github.com/zingolabs/zaino/issues/983

Nice catch!

File: zaino-state/src/chain_index/tests.rs [hunk 7]
```diff
@@ -2,7 +2,9 @@
 
 pub(crate) mod finalised_state;
 pub(crate) mod mempool;
+mod mockchain_tests;
 mod proptest_blockgen;
+mod sync_loop;
 pub(crate) mod vectors;
 
 pub(crate) fn init_tracing() {
```
Comment (nachog00) [inline zaino-state/src/chain_index/tests.rs:10]: This `init_tracing` bit should be defined in `zaino-common::logging` and adhere to the new tracing standard

File: zaino-state/src/chain_index/tests/sync_loop.rs [hunk 8]
```diff
@@ -18,12 +24,52 @@ async fn survives_transient_source_failure() {
...
+#[tokio::test(flavor = "multi_thread")]
+async fn escalates_to_critical_after_persistent_failure() {
+    let (_blocks, _indexer, index_reader, mockchain) =
+        load_test_vectors_and_sync_chain_index(true).await;
+
+    let start = Instant::now();
+    mockchain.set_failing(true);
+
+    // Poll until CriticalError rather than sleeping a fixed duration.
+    loop {
```
Comment (nachog00) [inline zaino-state/src/chain_index/tests/sync_loop.rs:57]: It seems like this loop runs indefintely if the only break isn't reached. aka, if there's no Critical status ever.

This might be mitigated by tooling (nextest) timeouts on tests... but we probably want to address this from the test itself.

Comment (zancas) [reply zaino-state/src/chain_index/tests/sync_loop.rs:57]: Nice find, I will double check:  https://github.com/zingolabs/zaino/issues/985

Comment (nachog00) [reply zaino-state/src/chain_index/tests/sync_loop.rs:57]: Resolving this as the assert would still catch it if the time was too long.

**Review by nachog00 — APPROVED** [review]
